'use strict';

var R = require('ramda');

module.exports =
angular.module('quill-grammar.services.lms.concept', [
  'underscore'
])
/*@ngInject*/
.factory('ConceptService', function (empiricalBaseURL, $http) {
  var url = empiricalBaseURL + '/concepts';

  this.get = function () {
    var accumulator = {concept_level_0: [],
                       concept_level_1: [],
                       concept_level_2: []};
    var groupByLevel = R.reduce(function(acc, concept) {
      switch(concept.level) {
        case 0:
          acc.concept_level_0.push(concept);
          break;
        case 1:
          acc.concept_level_1.push(concept);
          break;
        case 2:
          acc.concept_level_2.push(concept);
          break;
      }
      return acc;
    }, accumulator);

    return $http.get(url).then(function(response) {
      var concepts = response.data.concepts;
      return groupByLevel(concepts);
    });

    // return $timeout(function () {
    //   var concepts = {
    //     concept_level_0: [
    //       'Active Voice',
    //       'Passive Voice',
    //       'Adjectives',
    //       'Adjectives to Adverbs: Consonant Ending',
    //       'Adjectives to Adverbs: Ending in Y',
    //       'Adjectives to Adverbs: Ending in E',
    //       'Adverbs',
    //       'Although',
    //       'Bare',
    //       'Bear',
    //       'Breath',
    //       'Can\'t',
    //       'Cannot',
    //       'Capitalize Addresses',
    //       'Capitalize Appropriate Words in Titles',
    //       'Capitalize Dates',
    //       'Capitalize Geographic Names',
    //       'Capitalize Holidays',
    //       'Capitalize Names of People',
    //       'Capitalize Product Names',
    //       'Capitalize the Beginning of a Quotation',
    //       'Capitalize the Beginning of a Sentence',
    //       'Clean',
    //       'Cleanse',
    //       'Collective Nouns',
    //       'Colons in Lists',
    //       'Commas after Introductory Prepositional Phrases',
    //       'Commas and Quotation Marks in Dialogue',
    //       'Commas for Addressing People',
    //       'Commas for Tag Questions',
    //       'Commas for Yes and No',
    //       'Commas in Addresses',
    //       'Commas in Dates',
    //       'Commas in Lists',
    //       'Commas in Numbers',
    //       'Common Nouns',
    //       'Proper Nouns',
    //       'Comparative Adjectives ending in Y',
    //       'Better',
    //       'Worse',
    //       'Comparative Adjectives',
    //       'And',
    //       'Or',
    //       'But',
    //       'So',
    //       'Correct Messy Sentences',
    //       'Both . . . And',
    //       'Either . . . Or',
    //       'Neither . . . Nor',
    //       'Not Only . . . But Also',
    //       'The',
    //       'These',
    //       'Those',
    //       'That',
    //       'This',
    //       'Don\'t',
    //       'Ending Periods',
    //       'Ever After',
    //       'Every Day',
    //       'Everyday',
    //       'Finally',
    //       'Finely',
    //       'Grease',
    //       'Greece',
    //       'Haven\'t',
    //       'I\'m',
    //       'I\'ve',
    //       'A',
    //       'An',
    //       'Intensive Pronouns',
    //       'Himself',
    //       'However',
    //       'Still',
    //       'Deer',
    //       'Irregular Nouns Ending with "F"',
    //       'Irregular Nouns Ending with "Fe"',
    //       'Irregular Nouns Ending with "O"',
    //       'Feet',
    //       'Foot',
    //       'Teeth',
    //       'Tooth',
    //       'Child',
    //       'Children',
    //       'People',
    //       'Person',
    //       'Men',
    //       'Women',
    //       'Geese',
    //       'Goose',
    //       'Mice',
    //       'Gone',
    //       'Hid',
    //       'Been',
    //       'Eaten',
    //       'Became',
    //       'Broke',
    //       'Built',
    //       'Came',
    //       'Did',
    //       'Went',
    //       'Dug',
    //       'Found',
    //       'Wrote',
    //       'Spoke',
    //       'Knew',
    //       'Made',
    //       'Lost',
    //       'Sat',
    //       'Saw',
    //       'Irregular Plural Nouns Ending with "F"',
    //       'Irregular Plural Nouns Ending with "Fe"',
    //       'Irregular Plural Nouns Ending with "O"',
    //       'It\'s (Contractions)',
    //       'It\'s (Commonly Confused Words)',
    //       'It\'s',
    //       'Its',
    //       'Let\'s',
    //       'Lets',
    //       'Loose',
    //       'Lose',
    //       'Marry',
    //       'Mary',
    //       'Meant',
    //       'Mint',
    //       'Meanwhile',
    //       'Misplaced Modifiers',
    //       'Can',
    //       'May',
    //       'Must',
    //       'Should',
    //       'Objective Pronouns',
    //       'Of',
    //       'Off',
    //       'Parallel Structure',
    //       'Past',
    //       'Passed',
    //       'Periods in Numbers',
    //       'Pleas',
    //       'Please',
    //       'Plural Possessive',
    //       'Singular Possessive',
    //       'Possessive Nouns',
    //       'Subjective Pronouns',
    //       'Possessive Pronouns',
    //       'Poor',
    //       'Pour',
    //       'Prepositional Phrases: Adverb',
    //       'At (Place)',
    //       'In (Place)',
    //       'On (Place)',
    //       'At (Time)',
    //       'In (Time)',
    //       'On (Time)',
    //       'Future Progressive',
    //       'Past Progressive',
    //       'Present Progressive',
    //       'Gender Pronoun Shift',
    //       'Number Pronoun Shift',
    //       'Pronoun Shift: Singular',
    //       'Pronoun Shift: Plural',
    //       'Quiet',
    //       'Quite',
    //       'Raise',
    //       'Razing',
    //       'Myself',
    //       'Itself',
    //       'Ourselves',
    //       'Yourself',
    //       'Yourselves',
    //       'Herself',
    //       'Him',
    //       'Regular Past Participles',
    //       'When',
    //       'Whose',
    //       'Who',
    //       'Whom',
    //       'Why',
    //       'Where',
    //       'Which',
    //       'Shone',
    //       'Shown',
    //       'Future Tense Verbs',
    //       'Past Tense Verbs',
    //       'Plural Nouns',
    //       'Singular Nouns',
    //       'Spaces with Periods',
    //       'Spaces with Punctuation',
    //       'Because',
    //       'Superlative Adjectives ending in Y',
    //       'Best',
    //       'Superlative Adjectives',
    //       'Worst',
    //       'Than',
    //       'Then',
    //       'That\'s',
    //       'Their',
    //       'There',
    //       'They\'re',
    //       'Throne',
    //       'Thrown',
    //       'To',
    //       'Too',
    //       'Two',
    //       'Two Adjectives',
    //       'Verb Mood Shift',
    //       'Verb Tense Shift',
    //       'Won\'t',
    //       'You\'re',
    //       'Your',
    //       'Omename.',
    //       'Omenamex2.',
    //       'Omenamex55.'
    //     ],
    //     concept_level_1: [
    //       'Active and Passive Voice',
    //       'Adjectives',
    //       'Adjectives to Adverbs',
    //       'Adverbs',
    //       'Although, All Though',
    //       'Bare, Bear',
    //       'Breath, Breathe',
    //       'Can\'t',
    //       'Cannot',
    //       'Capitalize Addresses',
    //       'Capitalize Appropriate Words in Titles',
    //       'Capitalize Dates',
    //       'Capitalize Geographic Names',
    //       'Capitalize Holidays',
    //       'Capitalize Names of People',
    //       'Capitalize Product Names',
    //       'Capitalize the Beginning of a Quotation',
    //       'Capitalize the Beginning of a Sentence',
    //       'Clean, Cleanse',
    //       'Collective Nouns',
    //       'Colons in Lists',
    //       'Commas after Introductory Prepositional Phrases',
    //       'Commas and Quotation Marks in Dialogue',
    //       'Commas for Addressing People',
    //       'Commas for Tag Questions',
    //       'Commas for Yes and No',
    //       'Commas in Addresses',
    //       'Commas in Dates',
    //       'Commas in Lists',
    //       'Commas in Numbers',
    //       'Common and Proper Nouns',
    //       'Comparative Adjectives',
    //       'Coordinating Conjunctions',
    //       'Correct Messy Sentences',
    //       'Correlative Conjunctions',
    //       'Definite Articles',
    //       'Demonstratives',
    //       'Don\'t',
    //       'Ending Periods',
    //       'Ever After',
    //       'Every Day, Everyday',
    //       'Finally, Finely',
    //       'Greece, Grease',
    //       'Haven\'t',
    //       'I\'m',
    //       'I\'ve',
    //       'Indefinite Articles',
    //       'Intensive Pronouns',
    //       'Introductory Words',
    //       'Irregular Nouns',
    //       'Irregular Plural Nouns',
    //       'Irregular Past Participles',
    //       'Irregular Past Tense Verbs',
    //       'It\'s, Its',
    //       'Let\'s',
    //       'Loose, Lose',
    //       'Mary, Marry',
    //       'Meant, Mint',
    //       'Misplaced Modifiers',
    //       'Modal Auxiliaries',
    //       'Objective Pronouns',
    //       'Of, Off',
    //       'Parallel Structure',
    //       'Passed, Past',
    //       'Periods in Numbers',
    //       'Please, Pleas',
    //       'Possessive Nouns',
    //       'Possessive Pronouns',
    //       'Pour, Poor',
    //       'Prepositional Phrases',
    //       'Prepositions of Location',
    //       'Prepositions of Time',
    //       'Progressive Tense',
    //       'Pronoun Shift',
    //       'Proper Nouns',
    //       'Quiet, Quite',
    //       'Raised, Razed',
    //       'Reflexive Pronouns',
    //       'Regular Past Participles',
    //       'Relative Pronouns',
    //       'Shown, Shone',
    //       'Simple Tense',
    //       'Singular And Plural Nouns',
    //       'Spaces with Periods',
    //       'Spaces with Punctuation',
    //       'Subjective Pronouns',
    //       'Subordinating Conjunctions',
    //       'Superlative Adjectives',
    //       'Than, Then',
    //       'That\'s',
    //       'There, They\'re, Their',
    //       'Thrown, Throne',
    //       'To, Too, Two',
    //       'Two Adjectives',
    //       'Verb Mood Shift',
    //       'Verb Tense Shift',
    //       'Won\'t',
    //       'You\'re',
    //       'You\'re, Your'
    //     ],
    //     concept_level_2: [
    //       'Structure',
    //       'Adjectives & Adverbs',
    //       'Commonly Confused Words',
    //       'Contractions',
    //       'Capitalization',
    //       'Nouns & Pronouns',
    //       'Punctuation',
    //       'Conjunctions',
    //       'Custom Activities',
    //       'Determiners',
    //       'Verbs',
    //       'Prepositions'
    //     ]
    //   };
    //   return _.chain(concepts)
    //     .map(function (level, key) {
    //       return [key, _.map(level, function (value, index) {
    //         return {
    //           uid: String(index),
    //           title: value
    //         };
    //       })];
    //     })
    //     .object()
    //     .value();
    // }, 200);
  };
  return this;
});
